name: Confounder Dev Deployment

on:
  push:
    branches:
      - ohbm

jobs:
  docker_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout correct branch
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    
    # Build and deploy docker dev images
    - name: Build & Deploy Docker dev image
      if: github.ref == 'refs/heads/ohbm'
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        echo 'Docker login'
        echo ''
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_KEY
        echo ''
        echo 'Building docker image...'
        echo ''
        cd container
        docker build . --tag switt4/confounder:dev
        echo ''
        echo 'Pushing docker image...'
        echo ''
        docker push switt4/confounder:dev
        echo ''
        echo 'Finished deploying docker image.'
